name: Deploy Finpal Docker Image to EC2

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  Deploy-FinPal:
    uses: mmathen/group7_Capstone_llmExplore/.github/workflows/finpalworkflow.yml@main
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
